name: chronicle
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/samyak039/chronicle.dart.git

environment:
  sdk: '>=2.19.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
